#!/bin/bash

make distclean

NAME="fbsplash-`cat VERSION`"
OLDDIR="`pwd`"

rm -fr fbsplash-*.tar.gz
cd ..
mv $OLDDIR $NAME

tar -zcvf $NAME.tar.gz $NAME/

mv $NAME $OLDDIR
mv $NAME.tar.gz $OLDDIR

cd $OLDDIR
